/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/HoveringDrone.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.hover.play();
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[0.01, 0.01, 0.01]}>
        <primitive object={nodes.root2} />
        <skinnedMesh
          geometry={nodes.drone44.geometry}
          material={nodes.drone44.material}
          skeleton={nodes.drone44.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/HoveringDrone.glb')
